### ISSUE TITLE
want rate as part of default network checks

### ISSUE THREAD

**Issue by bixu** [circonus-labs/leo#6]
Mbit/s or Kbit/s would be helpful in addition to the current counters

**Comment by melcabel** [comment]
Hi Blake,

For this issue I am a little confused about which rate you are asking for? Also if you want us to change the measurements of the other counters to Mbits/s or Kbit/s, or just have the unit of the new rate be one of these.

Melanie Abel

**Comment by bixu** [comment]
Sorry for the confusion.  What I meant is that I think it would be more helpful if the existing metrics were displayed in either megabits per second or kilobits per second, as these are the usual units we use for network activity.

**Comment by melcabel** [comment]
All good. Thanks for clearing that up!
